global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'servidor'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'aplicacion_nodejs'
    static_configs:
      - targets: ['app-node:3000']