name: CI Pipeline - Análisis SAST con SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQube-analysis:
    name: Análisis de Calidad de Código
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonación del repositorio (Checkout)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Requerido por SonarQube para un análisis histórico completo

      - name: Ejecución de Escáner SonarQube
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=mi-proyecto-gestion-sw
            -Dsonar.qualitygate.wait=true
